name: Build Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev freeglut3-dev

      - name: configure
        run: ./configure

      - name: make
        run: |
          mkdir obj bin
          make
